### ISSUE TITLE
west.yml: URL for rpmsg_lite is redundant, use defined remotes

### ISSUE THREAD

**Issue by s-hemer** [nxp-mcuxpresso/mcux-sdk#129]
This is just cosmetics but it would be only deleting this line: https://github.com/nxp-mcuxpresso/mcux-sdk/blob/5e915fe4cfc1a30b0f455286027e29d3f805cf60/west.yml#L38

**Comment by s-hemer** [comment]
Ok, now I myself got confused. Deleting worked as https://github.com/NXPmicro/rpmsg-lite exists, yet the potentially correct solution should be replacing the line with `remote: nxp-mcuxpresso` obviously.

**Comment by mcuxsusan** [comment]
Thanks for suggesting this. Per my understanding, west will take URL assignment as priority when a project has URL key. But, yes you are right the rgmsg-lite repository is also located in remote: nxp-mcuxpresso, then remove the URL line also works because when URL is not defined, the project will fall to use the default remote nxp-mcuxpresso.

**Comment by s-hemer** [comment]
Of course it works anyways. As I wrote, it is a matter of cosmetics/cleanliness. If one has defined a remote, it is confusing to read the same one as URL again and you just wonder if you missed something.
