### ISSUE TITLE
Simplify include <stdio.h>

### ISSUE THREAD

**Issue by Hadatko** [nxp-mcuxpresso/mcux-sdk#40]
This condition can be theoreticaly be removed
https://github.com/NXPmicro/mcux-sdk/blob/e84ccf99a203bbbd8872d9953c8d3b57864d484b/utilities/debug_console/debug_console/fsl_debug_console.h#L51
 and include can be moved under
https://github.com/NXPmicro/mcux-sdk/blob/e84ccf99a203bbbd8872d9953c8d3b57864d484b/utilities/debug_console/debug_console/fsl_debug_console.h#L76
or am i wrong?

**Comment by mcuxsusan** [comment]
Hi @lylezhu2014, could you help explain?

**Comment by Hadatko** [comment]
![image](https://user-images.githubusercontent.com/13130700/146151245-6b9ea732-3990-4cbf-9038-ea515716ebe9.png)
![image](https://user-images.githubusercontent.com/13130700/146151296-4a384841-afc0-44d5-b810-52543461abfb.png)

**Comment by mcuxsusan** [comment]
Hi @Hadatko, thanks for your patience. @lylezhu2014, please help update your progress here.

**Comment by lylezhu2014** [comment]
> ![image](https://user-images.githubusercontent.com/13130700/146151245-6b9ea732-3990-4cbf-9038-ea515716ebe9.png) ![image](https://user-images.githubusercontent.com/13130700/146151296-4a384841-afc0-44d5-b810-52543461abfb.png)

Hi @Hadatko , I don't see the difference between this change and the previous one. Does this change have any special effect for you?

**Comment by Hadatko** [comment]
Less condition more transparent? And also redundant include for disabled debug console?

**Comment by bdcncdcdvd** [comment]
Hi, @Hadatko. I don't think it is more transparent if make some changes. Because now the "fsl_debug_console.h" has been changed as follow:
![image](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/104994478/675141d1-66cd-460c-90f9-5dce661e8731)
As we can see, there are one condition be added, if we update the code as you said then the follow codes will be redundant：
![image](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/104994478/3eabc08c-b9b4-43e6-9b3b-623813969993)
![image](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/104994478/e09accb1-1018-43e4-a740-b0b45cdbb7bd)

**Comment by mcuxsusan** [comment]
It seems the header file only needs to be included under some conditions, that's design intention, so I am gonna to close the issue.
